### PR TITLE
Fixed main menu FadeIn/FadeOut buttons glitch.

### LINKED ISSUE #140: Chapter 4: Main Menu fade in/out doesn't work
**Describe the bug**

a) Fade Out: 
We call `this._menuContainer.isVisible = false;` before our fading logic starts to work. So, we hide menu before our smooth transition.
I think that the line mentioned above should be inside of the `OnEnded` callback.
b) Fade In:
`_onMenuEnter` is never called. Also, we need to set alpha to 0 right after `menuContainer` creation. Because initially we don't show a menu.

**Expected behavior**

- Main menu and its' children should smoothly fade in when initially run
- When dismissed/exited, the main menu and all its' children controls should smoothly fade out

**Additional context**

Aggregated by #127

### PR DESCRIPTION
**Pull request by AlexanderPolenov**
On develop branch FadeIn/FadeOut works a little bit better, so I just fixed the button alpha property glitch. I also disable buttons during transition, to prevent clicking on them in order to avoid potential glitches.
On the modern BabylonJS versions disabling the buttons draws them in a grayscale. We can try to find a way to suppress this behavior, but honestly, I don't think it looks bad. It explicitly says that the menu is in transition, so user needs to keep hands away.

### CODE REVIEW

File: src/mainMenuScene.js [hunk 1]
```diff
@@ -42,6 +42,7 @@ class MainMenuScene {
     onHighScoreActionObservable = new Observable();
     highScoreDialog;
     isTopMost = true;
+    buttons = [];
```
Comment (jelster) [inline src/mainMenuScene.js]: since `selectedItem` refers to the currently selected Menu Item, this could be renamed. As well, because we are using `_menuGrid` as the container for these "buttons", could we make this a get property accessor that returns `this._menuGrid.children`? Here's what I'm thinking (can't remember OTOMH if it's children or `getChildren`, but I hope the idea is there):

 ```
get menuItems() {
    return this._menuGrid.children
```

Then, we could remove the possibility of later someone adding a new menu item and forgetting to push it into an array

File: src/mainMenuScene.js [hunk 2]
```diff
@@ -301,20 +304,28 @@ class MainMenuScene {
     }
 
     _onMenuEnter(duration) {
-        let fadeIn = 0;
         const fadeTime = duration || 1500;
         this._menuContainer.isVisible = true;
         this._menuContainer.alpha = 0;
+
+        // To prevent clicking on buttons during transition.
+        this.buttons.forEach((btn) => {
```
Comment (jelster) [inline src/mainMenuScene.js]: this could be `this._menuGrid.children.forEach`, or per above comment `this.menuItems.forEach`

File: src/mainMenuScene.js [hunk 3]
```diff
@@ -301,20 +304,28 @@ class MainMenuScene {
...
+            btn.alpha = 0;
+        });
+
         const timer = setAndStartTimer({
             timeout: fadeTime,
             contextObservable: this._scene.onBeforeRenderObservable,
             onTick: (d) => {                
                 const currAmt = Scalar.SmoothStep(0, 1, d.completeRate);
                 this._menuContainer.alpha = currAmt;
+                this.buttons.forEach((btn) => btn.alpha = currAmt);
```
Comment (jelster) [inline src/mainMenuScene.js]: similar to above, this could be `menuItems`

**Review by jelster — CHANGES_REQUESTED** [review]
Thanks for putting this together if I haven't already said it! 😄 

Something was troubling me about the transparency behavior of these buttons so I did some digging on the [BJS forums ](https://forum.babylonjs.com/t/babylongui-container-transparency/19177/3)and found this relatively new [feature for the GUI ](https://github.com/BabylonJS/Babylon.js/pull/10125).

Basically, instead of having to loop over the menu items during transitions, you would set this renderToIntermediateTexture property to `true` to have it work like we would expect it to. 

Would you mind giving it a try and pushing those changes here? The PR will be updated with a comment to where you can find the staging environment it will create for it

**Comment by AlexanderPolenov** [comment]
I made changes. `renderToIntermediateTexture` fixes the alpha error with buttons, however we still need to disable them during transition. I think it's the right thing to do.

**Comment by jelster** [comment]
hey sorry I've been quiet on this - been under the weather. I'll be circling back to this in the next few days though - thanks for your patience!

**Review by jelster — APPROVED** [review]

**Comment by jelster** [comment]
> disabling the buttons draws them in a grayscale. We can try to find a way to suppress this behavior, but honestly, I don't think it looks bad. It explicitly says that the menu is in transition, so user needs to keep hands away.

I watched it a few times to get a good sense of this, and I agree it's possible for us to set the disabled styles such that we don't have the greyscale transition but I don't see it being a bad thing necessarily either. 

LGTM - and thanks!
